// <auto-generated />
using System;
using E18I4DABH4Gr4.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace E18I4DABH4Gr4.Migrations
{
    [DbContext(typeof(SmartGridDBContext))]
    [Migration("20181214140651_newSmartGrid")]
    partial class newSmartGrid
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("E18I4DABH4Gr4.Models.Prosumer", b =>
                {
                    b.Property<string>("ProsumerId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ConsumerForeignKey");

                    b.Property<int>("KWhAmount");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int?>("ProducerForeignKey");

                    b.Property<int>("prosumerType");

                    b.HasKey("ProsumerId");

                    b.HasIndex("ConsumerForeignKey");

                    b.HasIndex("ProducerForeignKey");

                    b.ToTable("Prosumers");
                });

            modelBuilder.Entity("E18I4DABH4Gr4.Models.SmartGrid", b =>
                {
                    b.Property<int>("SmartGridId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ConsumerForeignKey");

                    b.Property<int>("ProducerForeignKey");

                    b.HasKey("SmartGridId");

                    b.ToTable("SmartGrids");
                });

            modelBuilder.Entity("E18I4DABH4Gr4.Models.Prosumer", b =>
                {
                    b.HasOne("E18I4DABH4Gr4.Models.SmartGrid")
                        .WithMany("Consumers")
                        .HasForeignKey("ConsumerForeignKey");

                    b.HasOne("E18I4DABH4Gr4.Models.SmartGrid")
                        .WithMany("Producers")
                        .HasForeignKey("ProducerForeignKey");
                });
#pragma warning restore 612, 618
        }
    }
}
